{% set name = "azure-quantum" %}
{% set version = "0.28.276174" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-quantum-{{ version }}.tar.gz
    sha256: 6fdb496c29e3b8e456061de161055a5709fe9d812a8294204a2d89abae20075a
  - url: https://raw.githubusercontent.com/microsoft/qdk-python/release/v{{ version }}/LICENSE
    sha256: c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - markdown >=3.4.1
    - python-markdown-math >=0.8
    - aiofile >=3.7.2,<4.0
    - aiohttp >=3.7.0,<4.0
    - azure-core >=1.26.2,<2.0.0
    - azure-identity >=1.12.0,<2.0.0
    - azure-storage-blob >=12.14.1,<13.0.0
    - deprecated >=1.2.12,<2.0
    - msrest >=0.7.1,<1.0
    - numpy >=1.21.0,<2.0
    - protobuf >=3.14.0,<4.0
    - python >=3.6
  run_constrained:
    - cirq-core ==0.15.0
    - cirq-ionq ==0.15.0
    - qiskit-ionq >=0.3.3
    - qiskit-terra >=0.19.1
    - qiskit-qir >=0.1.0b12

test:
  imports:
    - azure.quantum
    - azure.quantum._authentication
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/qdk-python
  summary: Python client for Azure Quantum
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
